name: CI

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.17.0'

    - name: Install dependencies
      run: npm install

    - name: Start application
      run: npm start &
      env:
        CI: true

    - name: Wait for application to be ready
      run: sleep 10

    - name: Run Cypress tests
      run: npm run cypress:ci

    - name: Produce Cypress test results
      uses: actions/upload-artifact@3
      with:
        name: cypress-test-results
        path: reports/functional
